services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - /home/srikanth/study/todo/todo-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "todos"
    networks:
      - todo-app
networks:
  todo-app:
    driver: bridge